package constants

// PkixOrganization ...
const PkixOrganization = "Tokaido"

// PkixLocality ...
const PkixLocality = "Shin-Osaka"

// PkixProvince ...
const PkixProvince = "Osaka"

// PkixCountry ...
const PkixCountry = "Japan"

// PkixOrganizationalUnit ...
const PkixOrganizationalUnit = "Tokaido Local Development Environment"

// PkixCommonName ...
const PkixCommonName = "*.tokaido.local"
