package constants

// CommonName ...
const CommonName = "tokaido.local"

// TopLevelHost ...
const TopLevelHost = "tokaido.local"

// WildcardHost ...
const WildcardHost = "*." + TopLevelHost

// KeyAlgorithm ...
const KeyAlgorithm = "rsa"

// KeySize ...
const KeySize = 2048

// PkixOrganization ...
const PkixOrganization = "Tokaido"

// PkixLocality ...
const PkixLocality = "Shin-Osaka"

// PkixProvince ...
const PkixProvince = "Osaka"

// PkixCountry ...
const PkixCountry = "JP"

// PkixOrganizationalUnit ...
const PkixOrganizationalUnit = "Tokaido Local Development Environment"

// CertEmailAddress ...
const CertEmailAddress = "developer@" + ProxyDomain
