package constants

import "path/filepath"

// CommonName ...
const CommonName = "local.tokaido.io"

// TopLevelHost ...
const TopLevelHost = "local.tokaido.io"

// WildcardHost ...
const WildcardHost = "*." + TopLevelHost

// SigningProfileName ...
const SigningProfileName = "tokaido"

// TenYearExpiryString ...
const TenYearExpiryString = "87600h"

// KeyAlgorithm ...
const KeyAlgorithm = "rsa"

// KeySize ...
const KeySize = 2048

// PkixOrganization ...
const PkixOrganization = "Tokaido Certificate Authority - Generation 3"

// PkixLocality ...
const PkixLocality = "Shin-Osaka"

// PkixProvince ...
const PkixProvince = "Osaka"

// PkixCountry ...
const PkixCountry = "JP"

// PkixOrganizationalUnit ...
const PkixOrganizationalUnit = "Tokaido Local Development Environment"

// CertEmailAddress ...
const CertEmailAddress = "developer@" + ProxyDomain

// CAFilename ...
const CAFilename = "proxy_ca"

// ClientCertFilename ...
const ClientCertFilename = "tokaido"

// TLSRoot is the root for all TLS certificates in ~/.tok/tls
var TLSRoot string = filepath.Join(".tok", "tls")

// CertificateAuthorityCertificatePath ...
var CertificateAuthorityCertificatePath string = filepath.Join("ca", "ca.crt")

// CertificateAuthorityKeyPath ...
var CertificateAuthorityKeyPath string = filepath.Join("ca", "ca.key")

// WildcardCertificatePath ...
var WildcardCertificatePath string = filepath.Join("proxy", "wildcard.crt")

// WildcardKeyPath ...
var WildcardKeyPath string = filepath.Join("proxy", "wildcard.key")
