project_name: tokaido
builds:
  - binary: tok-macos-intel
    id: tok-macos-intel
    goos:
      - darwin
    goarch:
      - amd64
  - binary: tok-macos-silicon
    id: tok-macos-silicon
    goos:
      - darwin
    goarch:
      - arm64

signs:
  - signature: "${artifact}.dmg"
    ids: ["tok-macos-silicon", "tok-macos-intel"]
    cmd: gon
    args: ["gon.hcl"]
    artifacts: all

archives:
  - id: binaries
    builds: ["macos"]
    format: binary


