package git

import (
	"bitbucket.org/ironstar/tokaido-cli/system/fs"
	"bitbucket.org/ironstar/tokaido-cli/utils"

	"bufio"
	"bytes"
	"fmt"
	"os"
	"strings"
)

// IgnoreDefaults - Append the baseline files that should be ignored in source control
func IgnoreDefaults() {
	AppendGitignore([]string{"docroot/sites/default/settings.tok.php", "docker-compose.tok.yml", ".tok/local"})
}

// AppendGitignore ...
func AppendGitignore(ignoreList []string) {
	f, err := os.Open(fs.WorkDir() + "/.gitignore")
	if err != nil {
		fmt.Println("There was an issue finding your .gitignore file", err)
		return
	}

	defer f.Close()

	ignoreMap := make(map[string]bool)
	for _, ignoreFile := range ignoreList {
		ignoreMap[ignoreFile] = true
	}

	var containsTokValues = false
	var buffer bytes.Buffer
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		if ignoreMap[scanner.Text()] {
			ignoreMap[scanner.Text()] = false
		}
		if strings.Contains(scanner.Text(), "# START Generated by Tokaido") {
			containsTokValues = true
		}
		buffer.Write([]byte(scanner.Text() + "\n"))
	}

	var ignoreString = ""
	for key := range ignoreMap {
		if ignoreMap[key] == true {
			ignoreString = ignoreString + key + "\n"
		}
	}

	if ignoreString != "" {
		if containsTokValues == true {
			buffer = utils.BufferInsert(buffer, "# START Generated by Tokaido", ignoreString)

			fs.Replace("./.gitignore", buffer.Bytes())
			return
		}

		buffer.Write([]byte(`
# START Generated by Tokaido
` + ignoreString + `
# END Generated by Tokaido
`))

		fs.Replace("./.gitignore", buffer.Bytes())
	}
}
