package drupaltmpl

// DocrootSitesDefaultSettings - (Append) docroot/sites/default/settings.php
var DocrootSitesDefaultSettings = `/*
* Generated by TOKAIDO
*/

if (file_exists($app_root . '/' . $site_path . '/settings.tok.php')) {
  include $app_root . '/' . $site_path . '/settings.tok.php';
}
?>
`

// DocrootSitesDefaultSettingsTok - docroot/sites/default/settings.tok.php
var DocrootSitesDefaultSettingsTok = `<?php

/**
 * @file
 * Configuration file for dynamic app environments.
 * Generated by TOKAIDO
 */

$databases['default']['default'] = [
  'host' => 'mysql',
  'database' => 'tokaido',
  'username' => 'tokaido',
  'password' => 'tokaido',
  'port' => 3306,
  'driver' => 'mysql',
  'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
  'prefix' => '',
];

$settings['file_private_path'] = $app_root . '/../files-private/';

?>
`
