package dockertmpl

var TokComposeYml = `# Generated by TOKAIDO
version: "2"
services:
  unison:
    image: onnimonni/unison
    environment:
      - UNISON_DIR=/tokaido/site
      - UNISON_UID=1001
      - UNISON_GID=1001
    ports:
      - "5000"
    volumes:
      - /tokaido/site
  syslog:
    image: tokaido/syslog:0.0.1
    volumes:
      - /tokaido/logs
  haproxy:
    user: "1005"
    image: tokaido/haproxy:0.0.1
    ports:
      - "8080"
      - "8443"
    depends_on:
      - varnish
      - nginx
  varnish:
    user: "1004"
    image: tokaido/varnish:0.0.2
    depends_on:
      - nginx
  nginx:
    user: "1002"
    image: tokaido/nginx:0.0.1
    volumes_from:
      - unison
      - syslog
    depends_on:
      - fpm
    ports: 
      - "8082"
  fpm:
    user: "1001"
    image: tokaido/fpm:0.0.2
    env_file: .env
    working_dir: /tokaido/site/
    volumes:
      - ./.env:/tokaido/config/.env
    volumes_from:
      - unison
      - syslog
    depends_on:
      - syslog
    ports:
      - "9000"
    environment:
      PHP_DISPLAY_ERRORS: "yes"
  memcache:
    image: memcached:1.5-alpine
  mysql:
    image: mysql:5.7
    volumes_from:
      - syslog
    environment:
      MYSQL_DATABASE: tokaido
      MYSQL_USER: tokaido
      MYSQL_PASSWORD: tokaido
      MYSQL_ROOT_PASSWORD: tokaido
  drush:
    env_file: .env
    image: tokaido/drush:0.0.1
    hostname: 'tokaido'
    ports:
      - "22"
    working_dir: /tokaido/site
    volumes:
      - ./.env:/tokaido/config/.env
    volumes_from:
      - unison
      - syslog
    environment:
      SSH_AUTH_SOCK: /ssh/auth/sock

`
