package unisontmpl

// SyncTemplateStr systemd template for background sync service
var SyncTemplateStr = `# Generated by Tokaido. Edits will be overwritten!
[Unit]
Description=File sync service for Tokaido {{.SyncName}} project

[Service]
Type=simple
WorkingDirectory={{.SyncDir}}
ExecStart=/usr/bin/unison {{.SyncName}}
Restart=on-failure`
