package unisontmpl

// SyncTemplateStr systemd template for background sync service
var SyncTemplateStr = `<!-- Generated by Tokaido. Edits will be overwritten! -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>Label</key>
        <string>tokaido.sync.{{.SyncName}}.plist</string>
    <key>ProgramArguments</key>
    <array>
          <string>/usr/local/bin/unison</string>
      <string>{{.SyncName}}</string>
    </array>
        <key>WorkingDirectory</key>
        <string>{{.SyncDir}}</string>
    <key>StandardErrorPath</key>
    <string>/Users/{{.Username}}/Library/Logs/tokaido.sync.{{.SyncName}}.err</string>
    <key>StandardOutPath</key>
    <string>/Users/{{.Username}}/Library/Logs/tokaido.sync.{{.SyncName}}.out</string>
    </dict>
</plist>`
