package snapshots

import (
	"fmt"
	"log"
	"os"
	"path/filepath"

	"github.com/ironstar-io/tokaido/conf"
	"github.com/ironstar-io/tokaido/system/console"
	"github.com/ironstar-io/tokaido/utils"
)

// Cleanup deletes all backup files generated by Tokaido
func Cleanup() {
	fmt.Println()
	p := filepath.Join(conf.GetConfig().Tokaido.Project.Path, "/.tok/local/snapshots")
	files, err := filepath.Glob(p + "/tokaido_*")
	if err != nil {
		console.Println("\n🙅‍  There was an error getting a list of database snapshots to delete", "")
		log.Fatal(err)
	}
	if len(files) == 0 {
		fmt.Println("💢  No snapshots were found which could be deleted by Tokaido")
		fmt.Println("")
		return
	}

	confirmDestroy := utils.ConfirmationPrompt(`💀  This will delete all database snapshots created by Tokaido. Are you sure?`, "n")
	if confirmDestroy == false {
		console.Println(`🕊  No snapshots were harmed`, "")
		return
	}

	for _, f := range files {
		fmt.Println("    Deleting snapshot " + filepath.Base(f))
		err = os.Remove(f)
		if err != nil {
			panic(err)
		}
	}

	if len(files) > 1 {
		fmt.Printf("🗑   Successfully deleted %d snapshots", len(files))
	} else if len(files) == 1 {
		fmt.Printf("🗑   Successfully deleted %d snapshot", len(files))
	}

	fmt.Println("")
	fmt.Println("")

	return
}
